<a href="https://colab.research.google.com/github/shresh15/PyTorch/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)
if torch.cuda.is_available():
  print("available gpu")

else:
  print("not available")


2.9.0+cpu
not available


In [ ]:
# CREATE TENSOR
torch.empty(2,3)



tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

TENSOR SHAPES

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape


torch.Size([2, 3])

In [ ]:
torch.tensor([1.3,2.5,5.9], dtype=torch.int32)

tensor([1, 2, 5], dtype=torch.int32)

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.clamp(d, min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [ ]:
  ###copy tensor
  #a=b makes the memory location same



In [ ]:
a=torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
b=a.clone()
b


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a[0][0]=10

In [ ]:
a

tensor([[10.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [ ]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])